name: Build and Push Docker Image to DockerHub

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t "${DOCKERHUB_USERNAME}"/flask-app:latest .
      - name: Login to DockerHub
        run: echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
      - name: Push Docker Image to DockerHub
        run: docker push "${DOCKERHUB_USERNAME}"/flask-app:latest

  update-manifest-stage:
    runs-on: ubuntu-latest
    needs: ['build-and-push']
    steps:
      - uses: actions/checkout@v3
        with:
          repository: RohanRusta21/flask-app-manifets
          ref: 'main'
          token: ${{ secrets.G_TOKEN }}
      - name: setup git config
        run: |
          git config --global user.email "rohanrustagi21@gmail.com"
          git config --global user.name "RohanRusta21"
          echo ${{ github.sha }}
          sed -i "s#${{ github.actor }}.*#${{ DOCKERHUB_USERNAME }}/flask-app:${{ github.sha }}#g" deploy.yml
          git add -A
          git commit -am "Update image for - ${{ github.sha }}"
      - run: echo ${{ github }}
      - run: git push origin main
